schemaVersion = 1

[default]
provider = "github"

[policies.pullRequests.prTitle]
required = true
pattern = '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z0-9_-]+\))?!?: .+'
label_if_missing = "title-invalid"

[policies.pullRequests.workItem]
required = true
pattern = '(?i)(fixes|closes|resolves|references|relates to)\s+(#\d+|GH-\d+|https://github\.com/[^/]+/[^/]+/issues/\d+|[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+#\d+)'
label_if_missing = "work-item-missing"

[policies.pullRequests.prSize]
# Enable PR size checking and labeling
enabled = true

# Fail the check for oversized PRs (XXL category - 500+ lines)
fail_on_oversized = true

# File patterns to exclude from size calculations
excluded_file_patterns = [
    "*.md",
    "*.txt",
    "Cargo.lock",
    "package-lock.json",
    "yarn.lock",
    "target/*",
    "docs/*",
]

# Prefix for size labels (will create labels like "size/XS", "size/S", etc.)
label_prefix = "size/"

# Add educational comments for oversized PRs
add_comment = true

# Custom size thresholds optimized for Rust projects
[policies.pullRequests.prSize.thresholds]
xs = 25  # 1-25 lines (small bug fixes)
s = 75   # 26-75 lines (minor features)
m = 150  # 76-150 lines (medium features)
l = 300  # 151-300 lines (large features)
xl = 500 # 301-500 lines (major changes)
# xxl = 501+ lines (requires breaking down)

[policies.bypassRules.title_convention]
enabled = true
users = ["pvandervelde", "release-bot"]

[policies.bypassRules.work_items]
enabled = false
users = []

[authentication]
auth_method = "app"

[webhooks]
port = 3100
