[workspace]
# disallow updating repositories with uncommitted changes
allow_dirty = false

# path of the git-cliff configuration
changelog_config = "cliff.toml"

# enable changelog updates
changelog_update = true

# update dependencies with `cargo update`
dependencies_update = false

# disable GitHub releases
git_release_enable = false

# create tags for the releases
git_tag_enable = false

# labels for the release PR
pr_labels = ["release"]

# enable publishing to crates.io
publish = false

# disallow packaging with uncommitted changes
publish_allow_dirty = false

# disable running `cargo-semver-checks`
semver_check = true

# set the path of all the crates to the changelog to the root of the repository
changelog_path = "./CHANGELOG.md"

# Options for the package I care the most, e.g. `my_main_package`.
[[package]]
name = "azure_functions"

# Enable git tags for this package
git_tag_enable = true

# Enable git releases for this package
git_release_enable = true
