[workspace]
allow_dirty = false
changelog_config = "cliff.toml"
changelog_update = false
dependencies_update = false
git_release_enable = false
git_tag_enable = false
publish = false
publish_allow_dirty = false
release_always = true
semver_check = true

[[package]]
name = "handler"
changelog_include = [
    "merge_warden_developer_platforms",
    "merge_warden_core",
    "merge_warden_cli",
]
changelog_path = "./CHANGELOG.md"
changelog_update = true
git_release_enable = true
git_release_name = "{{ version }}"
git_tag_enable = true
git_tag_name = "{{ version }}"
pr_labels = ["release"]
pr_name = "chore: release {{ version }}"
