[workspace]
# disallow updating repositories with uncommitted changes
allow_dirty = false

# path of the git-cliff configuration
changelog_config = "cliff.toml"

# enable changelog updates
changelog_update = false

# update dependencies with `cargo update`
dependencies_update = false

# disable GitHub releases
git_release_enable = false

git_release_name = "{{ version }}"

# create tags for the releases
git_tag_enable = false

git_tag_name = "{{ version }}"

# labels for the release PR
pr_labels = ["release"]

# enable publishing to crates.io
publish = false

# disallow packaging with uncommitted changes
publish_allow_dirty = false

# disable running `cargo-semver-checks`
semver_check = true

# set the path of all the crates to the changelog to the root of the repository
changelog_path = "./CHANGELOG.md"

pr_name = "chore: release {{ version }}"

release_always = false

# Options for the package I care the most, e.g. `my_main_package`.
[[package]]
name = "handler"

# Enable git tags for this package
git_tag_enable = true

# Enable git releases for this package
git_release_enable = true

# enable the changelog for this package
changelog_update = true

# set the path of the changelog to the root of the repository
changelog_path = "./CHANGELOG.md"
