[package]
name = "merge-warden-core"
version = "0.1.0"
edition = "2021"
description = "Core business logic for Merge Warden PR validation"
license = "MIT"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
lazy_static = "1.4.0"

[dev-dependencies]
proptest = "1.6.0"
