name: Deploy binaries

on:
  workflow_dispatch:
#  push:
#    # Only run the deploy when we do a tag push
#    tags:
#      - '[0-9]+.[0-9]+.[0-9]+'
#      - '!*-rc[0-9]+'
  release:
    types:
      - published

# Sets permissions of the GITHUB_TOKEN to allow deployment to Azure
permissions:
  contents: read
  id-token: write

jobs:
  deploy_to_azure:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@a94a3b62ee018ef5346cb08fd0d63d93811fe691 # v3.0.0
      with:
        versionSpec: '6.0.0'

    - name: Determine Version
      id: get-version # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@a94a3b62ee018ef5346cb08fd0d63d93811fe691 # v3.0.0
      with:
        useConfigFile: true

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable # v1
      with:
        target: x86_64-unknown-linux-musl
        toolchain: stable

    - name: Install cargo binstall
      uses: cargo-bins/cargo-binstall@main

    - name: Install cross
      run: cargo binstall cross --no-confirm --no-track

    - uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2

    - name: Build az_handler
      run: |
        cross build --release --package az_handler --target x86_64-unknown-linux-musl --target-dir target/temp

    - name: show directories after compile
      run: |
        ls -la
        ls -la target
        ls -la target/temp
        ls -la target/temp/x86_64-unknown-linux-musl
        ls -la target/temp/x86_64-unknown-linux-musl/release

    # Copy the files for the azure function into a single directory
    #
    # For the azure function we need the following directories and files in the following layout.
    # Where [D] means directory and [F] means file
    #
    # [D] <function_name>       --> <target>/<function_name>
    #     [F] function.json     --> <target>/<function_name>/function.json
    # [F] host.json             --> <target>/host.json
    # [F] local.settings.json   --> <target>/local.settings.json
    # [F] az_handler               --> <target>/az_handler
    - name: Copy Azure functions configs
      run: |
        mkdir -p target/func/merge_warden
        cp -r ./target/temp/x86_64-unknown-linux-musl/release/az_handler target/func
        cp -r ./configs/az_func/merge_warden/* target/func/merge_warden
        cp -r ./configs/az_func/host.json target/func
        cp -r ./configs/az_func/local.settings.json target/func

    - name: show directories after assemble
      run: |
        ls -la
        ls -la target
        ls -la target/func
        ls -la target/func/merge_warden

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

    - name: Azure Login
      uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Terraform Init
      run: terraform init
      working-directory: ops/azure
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_USE_OIDC: true

    - name: Create GitHub App Key File
      run: printf '%s\n' "${{ secrets.GH_APP_PRIVATE_KEY }}" > ops/azure/gh_app_key.pem
      shell: bash # Explicitly use bash for redirection

    - name: Terraform Apply
      working-directory: ops/azure
      run: |
        terraform apply -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_USE_OIDC: true
        TF_VAR_GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
        TF_VAR_GITHUB_APP_PRIVATE_KEY_PATH: ops/azure/gh_app_key.pem
        TF_VAR_GITHUB_WEBHOOK_SECRET: ${{ secrets.GH_WEBHOOK_SECRET }}
        TF_VAR_META_GIT_SHA: ${{ github.sha }}
        TF_VAR_META_VERSION: ${{ steps.get-version.outputs.majorMinorPatch }}

    - name: Remove GitHub App Key File
      if: always()
      run: rm ops/azure/gh_app_key.pem
      shell: bash

    # Don't use the publish profile for custom handlers
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@fd80521afbba9a2a76a99ba1acc07aff8d733d11 # v1
      with:
        app-name: p-aue-tf-mergew-function
        package: ${{ github.workspace }}/target/func

  publish-cli:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: aarch64-unknown-linux-musl
            os: ubuntu-22.04
          - target: aarch64-pc-windows-msvc
            os: windows-2022
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: x86_64-unknown-linux-musl
            os: ubuntu-22.04
          - target: x86_64-pc-windows-msvc
            os: windows-2022
          - target: x86_64-unknown-freebsd
            os: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
        if: startsWith(matrix.os, 'ubuntu') && !contains(matrix.target, '-musl')

      - uses: taiki-e/install-action@v2
        with:
          tool: cross
        if: contains(matrix.target, '-musl')

      - run: echo "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static" >> "${GITHUB_ENV}"
        if: endsWith(matrix.target, 'windows-msvc')

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: merge_warden_cli
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
