name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write # To update Cargo.toml, CHANGELOG.md, create tags
  pull-requests: write # To create/update the release PR

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'pvandervelde' }} # Keep the owner check
    steps:
      # Generate GitHub App token for permissions
      - name: Generate GitHub token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2
        id: generate-token
        with:
          app-id: ${{ secrets.RELEASE_PLZ_APP_ID }} # Reuse existing secrets
          private-key: ${{ secrets.RELEASE_PLZ_APP_PRIVATE_KEY }} # Reuse existing secrets

      # Run Release Please action
      - name: Run Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ steps.generate-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      # Output whether a release was created/proposed
      - name: Output release status
        run: echo "Release created/proposed? ${{ steps.release.outputs.release_created }}"
