name: Test Prepare Release Script

on:
  workflow_dispatch:
  # Optionally, run on push to a test branch
  # push:
  #   branches:
  #     - "**"

permissions:
  contents: write
  pull-requests: write

jobs:
  test-prepare-release:
    name: Test Prepare Release Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Set up GH CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2

      - name: Install cargo binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install git-cliff
        run: cargo install git-cliff

      - name: Install conventional_commits_next_version
        run: cargo install conventional_commits_next_version

      - name: Generate test version and release notes
        id: test_version
        run: |
          TEST_VERSION="0.0.$(date +%s)"
          echo "TEST_VERSION=${TEST_VERSION}" >> $GITHUB_OUTPUT
          echo "Test release notes for version ${TEST_VERSION}" > test_release_notes.md

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20

      - name: Run prepare-release.js (test)
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          node .github/scripts/prepare-release.js "${{ steps.test_version.outputs.TEST_VERSION }}" test_release_notes.md
